project_id = "idvwckpcsktnplnvwvba"

[functions.bulk-import-colleges]
verify_jwt = true

[functions.send-email-verification]
verify_jwt = true

[functions.verify-email-code]
verify_jwt = true

[functions.sitemap]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = true

[functions.verify-razorpay-payment]
verify_jwt = true
